apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: production
  name: prod-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.global-static-ip-name: prod-ip
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: prod-service
              servicePort: 8000
