apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: production
  name: prod-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: prod-service
              servicePort: 8000
