steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f',
      './server/deployment/prod/Dockerfile',
      '-t',
      'gcr.io/group-video-chat/prod-group-video-chat:$BUILD_ID',
      './server'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'gcr.io/group-video-chat/prod-group-video-chat:$BUILD_ID'
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      'set',
      'image',
      'deployment/prod-deployment',
      'prod-group-video-chat=gcr.io/group-video-chat/prod-group-video-chat:$BUILD_ID',
      '--namespace',
      'production'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=group-video-chat'