apiVersion: cert-manager.io/v1alpha1
kind: Issuer
metadata:
  name: sabachka-cert
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: saba.chikhina@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: sabachka-cert
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx