steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f',
      './server/deployment/dev/Dockerfile.dev',
      '-t',
      'gcr.io/ticketing-dev-281211/dev-group-vide-chat:$BUILD_ID',
      './server'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      'gcr.io/ticketing-dev-281211/dev-group-vide-chat:$BUILD_ID'
    ]
  - name: gcr.io/cloud-builders/kubectl
    args: [
      'set',
      'image',
      'deployment/dev-deployment',
      'dev-group-vide-chat=gcr.io/ticketing-dev-281211/dev-group-vide-chat:$BUILD_ID',
      '--namespace',
      'development'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=group-video-chat'