apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: prod-client-deployment
spec:
  selector:
    matchLabels:
      app: prod-client
  template:
    metadata:
      labels:
        app: prod-client
    spec:
      containers:
        - name: prod-group-video-chat-client
          image: gcr.io/group-video-chat/prod-group-video-chat-client
---
apiVersion: v1
kind: Service
metadata:
  name: prod-client-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: prod-client
  ports:
    - port: 80
      name: prod-client
      protocol: TCP
      targetPort: 80